version: '3.8'

services:
  mongo_service:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app_service:
    image: aa12037/flask-app:latest
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongo_service

volumes:
  mongo-data: