apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-replica-controller
spec:
  replicas: 2
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: aa12037/flask-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
          imagePullPolicy: Always
